### ISSUE TITLE
Checking SE in Bottleneck

### ISSUE THREAD

**Issue by teengineer** [Vandalious/MobileNetV3#1]
Hey, this work is amazing. 
 I cant find SE checking for bottleneck. Can you explain me how did you think this. 

![image](https://github.com/user-attachments/assets/41e66d68-738f-4566-8020-d837925a0b3f)

**Comment by arawxx** [comment]
That was an actually nice point! I never noticed it in the paper. Thanks.
I just updated the repo with this change, now the `Bottleneck` class takes in an `se` input argument indicating whether or not it should include an Squeeze-and-Excite layer or not, and the argument has been set true on appropriate layers. I have also added some docstrings for better readability :)

**Comment by teengineer** [comment]
Anytime. 
Sounds brilliant. Also thank you for updating and docstring.
